#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Context.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rContext.proto\x12\x05proto\x1a\x1bgoogle/protobuf/empty.proto\"+\n\nLogMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x10\n\x08logLevel\x18\x02 \x01(\t\"\xfa\x01\n\rPulsarMessage\x12\r\n\x05topic\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\x0c\x12\x11\n\tmessageId\x18\x03 \x01(\t\x12\x12\n\nproperties\x18\x04 \x01(\t\x12\x14\n\x0cpartitionKey\x18\x05 \x01(\t\x12\x12\n\nsequenceId\x18\x06 \x01(\t\x12\x1b\n\x13replicationClusters\x18\x07 \x01(\t\x12\x1a\n\x12\x64isableReplication\x18\x08 \x01(\x08\x12\x16\n\x0e\x65ventTimestamp\x18\t \x01(\x05\x12\x11\n\tdeliverAt\x18\n \x01(\x05\x12\x14\n\x0c\x64\x65liverAfter\x18\x0b \x01(\x05\"\x17\n\tMessageId\x12\n\n\x02id\x18\x01 \x01(\x0c\"\x19\n\x06Record\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\"/\n\nMetricData\x12\x12\n\nmetricName\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"I\n\tPartition\x12\x11\n\ttopicName\x18\x01 \x01(\t\x12\x16\n\x0epartitionIndex\x18\x02 \x01(\x05\x12\x11\n\tmessageId\x18\x03 \x01(\x0c\x32\x8f\x03\n\x07\x43ontext\x12\x32\n\x03Log\x12\x11.proto.LogMessage\x1a\x16.google.protobuf.Empty\"\x00\x12\x39\n\x07Publish\x12\x14.proto.PulsarMessage\x1a\x16.google.protobuf.Empty\"\x00\x12\x38\n\rCurrentRecord\x12\x16.google.protobuf.Empty\x1a\r.proto.Record\"\x00\x12<\n\rRecordMetrics\x12\x11.proto.MetricData\x1a\x16.google.protobuf.Empty\"\x00\x12\x32\n\x04Seek\x12\x10.proto.Partition\x1a\x16.google.protobuf.Empty\"\x00\x12\x33\n\x05Pause\x12\x10.proto.Partition\x1a\x16.google.protobuf.Empty\"\x00\x12\x34\n\x06Resume\x12\x10.proto.Partition\x1a\x16.google.protobuf.Empty\"\x00\x42,\n!org.apache.pulsar.functions.protoB\x07\x43ontextb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Context_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n!org.apache.pulsar.functions.protoB\007Context'
  _LOGMESSAGE._serialized_start=53
  _LOGMESSAGE._serialized_end=96
  _PULSARMESSAGE._serialized_start=99
  _PULSARMESSAGE._serialized_end=349
  _MESSAGEID._serialized_start=351
  _MESSAGEID._serialized_end=374
  _RECORD._serialized_start=376
  _RECORD._serialized_end=401
  _METRICDATA._serialized_start=403
  _METRICDATA._serialized_end=450
  _PARTITION._serialized_start=452
  _PARTITION._serialized_end=525
  _CONTEXT._serialized_start=528
  _CONTEXT._serialized_end=927
# @@protoc_insertion_point(module_scope)
